version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # back:
  #   build:
  #     context: ./back
  #   volumes:
  #     - ./back:/app
  #     - /app/node_modules
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NODE_ENV=development
  #   profiles:
  #     - dev
