# Use node as the base image
FROM node:18-alpine
# Update npm to version 7
RUN npm i -g npm@8.1.2

# Set the working directory
WORKDIR /app

# Copy files specifying dependencies
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
COPY .npmrc ./
RUN yarn install --check-files



# Copy all the files
COPY . .

# Expose the port the server listens to
EXPOSE 3005

# Make server to serve admin built files
# ENV SERVE_STATIC_ROOT_PATH=admin-ui/build

CMD ["npm" , "run" ,"start:debug"]
