# Use node as the base image
FROM node:20.13.1-alpine
# Update npm to version 7
RUN npm i -g npm@8.1.2

# Set the working directory
WORKDIR /app

# Copy files specifying dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all the files
COPY . .

# Expose the port the server listens to
EXPOSE 3001

# Make server to serve admin built files

CMD ["npm" , "run" ,"start"]
